"""WinAir tenant — structure only, Pricing module ONLY (tenant, user, RBAC, view).

Adds a real airline tenant "WinAir" (slug='wm') that mirrors the ALT/JY
airline pattern but is Pricing-only:

  * tenant row              slug='wm', display 'WinAir - WM'
  * app_user                wm@airline.com / bcrypt('WMairline@2026'),
                            must_change_password=TRUE, TENANT_ADMIN
  * role_binding            TENANT_ADMIN for the WM user
  * tenant_feature          Pricing-relevant subset only (airline module +
                            generic capabilities); Velocity/dashboard/cruise
                            features omitted
  * vw_airline_cpi_wm_snapshot   exact clone of vw_airline_cpi_jy_snapshot,
                                 predicate tenant_code='WM'

NO velocity view and NO Superset provisioning this build (Pricing-only).

The WM airline view is derived from the live JY view definition via
pg_get_viewdef + a single predicate substitution, so it stays
column-for-column identical to JY (mirrors migration 030).

The password hash is precomputed by a /tmp script and embedded as a literal
bcrypt digest — the plaintext password never appears in this migration.

Revision ID: 034
Revises: 033
Create Date: 2026-06-18
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "034"
down_revision: Union[str, None] = "033"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed UUIDs (continue the ff / 66 conventions for the new tenant/user)
TENANT_WM = "ff000000-0000-0000-0000-000000000001"
USER_WM = "66666666-0000-0000-0000-000000000001"

# Precomputed bcrypt('WMairline@2026') — generated by /tmp/wm_hash.py against
# the same passlib CryptContext(schemes=["bcrypt"]) the app verifies with.
# No plaintext password is stored in this migration.
WM_PWD_HASH = "$2b$12$PYc9UrQ4sj1q/X1p/IT3x.4AbzJ7/Y7rC3ZrA0LVzZYV04Q7GyZva"

# Pricing-relevant tenant_feature subset for WM. Velocity is not a feature row
# (it is the airline module's 2nd tab, suppressed in the frontend); dashboard
# features (superset_embed, anomaly_detection), cruise (cfl) and custom_branding
# are intentionally omitted for this Pricing-only build.
_FEATURES = [
    ("airline",      "Airline Module",     "module",     True),
    ("alerts",       "Alerting",           "capability", True),
    ("audit",        "Audit Log",          "capability", True),
    ("contracts",    "Contract Overlays",  "capability", True),
    ("exports",      "CSV / Excel Export", "capability", True),
    ("saved_views",  "Saved Views",        "capability", True),
]


def upgrade() -> None:
    conn = op.get_bind()

    # ── tenant ──
    conn.execute(sa.text(
        "INSERT INTO tenant (id, slug, display_name, is_active) "
        "VALUES (:id, 'wm', 'WinAir - WM', true) "
        "ON CONFLICT (id) DO NOTHING"
    ), {"id": TENANT_WM})

    # ── app_user (real tenant: TENANT_ADMIN, must_change_password=TRUE) ──
    conn.execute(sa.text("""
        INSERT INTO app_user (id, tenant_id, email, display_name, password_hash,
                              must_change_password, is_active, failed_login_count, locked_until)
        VALUES (:uid, :tid, 'wm@airline.com', 'WinAir Admin', :h,
                true, true, 0, NULL)
        ON CONFLICT (id) DO NOTHING
    """), {"uid": USER_WM, "tid": TENANT_WM, "h": WM_PWD_HASH})

    # ── role_binding ──
    conn.execute(sa.text("""
        INSERT INTO role_binding (tenant_id, user_id, role)
        VALUES (:tid, :uid, 'TENANT_ADMIN')
        ON CONFLICT DO NOTHING
    """), {"tid": TENANT_WM, "uid": USER_WM})

    # ── tenant_feature (Pricing-relevant subset) ──
    for code, label, category, enabled in _FEATURES:
        conn.execute(sa.text("""
            INSERT INTO tenant_feature (tenant_id, code, label, category, enabled)
            VALUES (:tid, :code, :label, :category, :enabled)
            ON CONFLICT (tenant_id, code) DO NOTHING
        """), {"tid": TENANT_WM, "code": code, "label": label,
               "category": category, "enabled": enabled})

    # ── WM airline view: exact clone of the JY view, predicate swapped to WM.
    #    No velocity view (Pricing-only). ──
    air_def = conn.execute(sa.text(
        "SELECT pg_get_viewdef('vw_airline_cpi_jy_snapshot', true)"
    )).scalar()
    air_wm = air_def.replace("tenant_code::text = 'JY'::text",
                             "tenant_code::text = 'WM'::text")
    if air_wm == air_def:
        raise RuntimeError("airline view predicate substitution failed (JY marker not found)")
    conn.execute(sa.text(f"CREATE VIEW vw_airline_cpi_wm_snapshot AS {air_wm}"))
    conn.execute(sa.text("GRANT SELECT ON vw_airline_cpi_wm_snapshot TO cpi_app"))


def downgrade() -> None:
    conn = op.get_bind()
    conn.execute(sa.text("DROP VIEW IF EXISTS vw_airline_cpi_wm_snapshot"))
    # Explicit child deletes first; deleting the tenant also CASCADEs any
    # remaining WM rows (app_user, role_binding, tenant_feature).
    conn.execute(sa.text("DELETE FROM role_binding WHERE tenant_id = :tid"), {"tid": TENANT_WM})
    conn.execute(sa.text("DELETE FROM tenant_feature WHERE tenant_id = :tid"), {"tid": TENANT_WM})
    conn.execute(sa.text("DELETE FROM app_user WHERE tenant_id = :tid"), {"tid": TENANT_WM})
    conn.execute(sa.text("DELETE FROM tenant WHERE id = :tid"), {"tid": TENANT_WM})
